// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPpRA_V81vuEJM1ujBdQawJuT1pmo53jY',
    appId: '1:235432217865:web:96e06c144a5fa8ab6d17d8',
    messagingSenderId: '235432217865',
    projectId: 'flutter-e-commerce-a9c66',
    authDomain: 'flutter-e-commerce-a9c66.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-a9c66.appspot.com',
    measurementId: 'G-T8RTB5D09R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-cGtuaiv7iisN_xOpFjfh5fPnovD0IcQ',
    appId: '1:235432217865:android:3f5e72b86f11dd236d17d8',
    messagingSenderId: '235432217865',
    projectId: 'flutter-e-commerce-a9c66',
    storageBucket: 'flutter-e-commerce-a9c66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsUoH68UI3no_UPDOAGusdMkd02EBPMtg',
    appId: '1:235432217865:ios:f9adc1c48e3717306d17d8',
    messagingSenderId: '235432217865',
    projectId: 'flutter-e-commerce-a9c66',
    storageBucket: 'flutter-e-commerce-a9c66.appspot.com',
    iosClientId: '235432217865-3pccko2ldub6fg0b06qrfe41fhu3pnj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSta',
  );
}
